### PR TITLE
Replace deprecated az configure with az config

### PR DESCRIPTION
**Pull request by dksimpson**
Replace instances of the deprecated 'az configure' with 'az config'.

This work is for story [1844036](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1844036).

### CODE REVIEW

**Comment by dksimpson** [comment]
Hi @dbradish-microsoft, this article is ready for review.

**Comment by dbradish-microsoft** [comment]
#sign-off for Azure CLI reference change.  @ashishonce or @narula0781 please review and merge.  Thank you.

**Comment by dbradish-microsoft** [comment]
@ishitam8, @atbagga , are either of you able to approve and merge this PR?

**Comment by atbagga** [comment]
> @ishitam8, @atbagga , are either of you able to approve and merge this PR?

We are no longer code owners in the repo. The required reviewers are added in the reviewers list.

**Comment by dbradish-microsoft** [comment]
Thanks, @atbagga, for letting me know.

**Review by harshiniks — APPROVED** [review]

**Review by chandrasekharmudili — APPROVED** [review]

**Pull request merged**
